name: gsheet_to_arb
version: 1.0.1
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ">=2.3.1"
  intl: ">=0.17.0 <0.21.0"
  intl_generator:
    git: https://github.com/shawoozy/intl_generator
      # url: https://github.com/kiwi-bop/intl_generator.git
      # ref: feature/migrationNullSafety
  path: ">=1.8.1"
  googleapis_auth: ^1.3.1
  googleapis: ^11.4.0
  code_builder: ">=4.1.0"
  json_annotation: "^4.5.0"
  file_utils: ">=1.0.1"
  logging: "^1.0.2"
  recase: "^4.0.0"

  quiver: "^3.1.0"

  yaml: ">=3.1.1"

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
  test: ^1.20.2
